services:
  docs:
    build:
      dockerfile: docs.Dockerfile
      context: .
    ports:
      - "1116:80"

  publish:
    build:
      context: .
      dockerfile: publish.Dockerfile

  publish-docs:
    build:
      context: .
      dockerfile: publish-docs.Dockerfile