name: Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 3 * * 3'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: current
      - run: npm install
      - run: npm audit --production --audit-level=low
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: docs
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
