name: Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 3 * * 3'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: current
      - run: npm install
      - run: npm audit --production --audit-level=low
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docs
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
